### ISSUE TITLE
环信ANR问题

### ISSUE THREAD

**Issue by husile333** [easemob/sdkexamples-android#60]
从正常WIFI切换至CHINAUNICOM等需要登陆的网络时会导致ANR应用无响应，anr日志如下

DALVIK THREADS (27):
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x72f272e0 self=0x41f07800
  | sysTid=26990 nice=0 cgrp=apps sched=0/0 handle=0x40163ec8
  | state=S schedstat=( 12627014130 9026153598 15297 ) utm=1161 stm=100 core=1 HZ=100
  | stack=0xbe7d8000-0xbe7da000 stackSize=8MB
  | held mutexes=
  at com.easemob.chat.core.XmppConnectionManager.startReconnectionThread(unavailable:-1)
  - waiting to lock <0x24cbdbfe> (a com.easemob.chat.core.XmppConnectionManager) held by thread 13
  at com.easemob.chat.core.XmppConnectionManager.access$3(unavailable:-1)
  at com.easemob.chat.core.XmppConnectionManager$1.onReceive(unavailable:-1)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:861)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5221)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by youniworld** [comment]
2.1.6已经修复
